# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseRestaurant(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Restaurant']] = 'Restaurant'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RestaurantActions[_PrismaModelT]':
        from .client import get_client

        return actions.RestaurantActions[_PrismaModelT](client or get_client(), cls)


class BaseFloor(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Floor']] = 'Floor'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FloorActions[_PrismaModelT]':
        from .client import get_client

        return actions.FloorActions[_PrismaModelT](client or get_client(), cls)


class BaseTable(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Table']] = 'Table'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TableActions[_PrismaModelT]':
        from .client import get_client

        return actions.TableActions[_PrismaModelT](client or get_client(), cls)


class BaseMember(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Member']] = 'Member'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MemberActions[_PrismaModelT]':
        from .client import get_client

        return actions.MemberActions[_PrismaModelT](client or get_client(), cls)


class BaseReservation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Reservation']] = 'Reservation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReservationActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReservationActions[_PrismaModelT](client or get_client(), cls)


