from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Restaurant',
    'Floor',
    'Table',
    'Member',
    'Reservation',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Restaurant': {
        'floors': 'Floor',
    },
    'Floor': {
        'restaurant': 'Restaurant',
        'tables': 'Table',
    },
    'Table': {
        'floor': 'Floor',
        'reservations': 'Reservation',
    },
    'Member': {
        'reservations': 'Reservation',
    },
    'Reservation': {
        'table': 'Table',
        'member': 'Member',
    },
}

# fmt: on