# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List['Serializable'],
    Dict[None, 'Serializable'],
    Dict[bool, 'Serializable'],
    Dict[float, 'Serializable'],
    Dict[int, 'Serializable'],
    Dict[str, 'Serializable'],
]


StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilter'],
                    },
    total=False,
)



class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilter'],
    },
    total=False,
)



class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilter'],
    },
    total=False,
)



class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilter'],
    },
    total=False,
)



class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilter'],
    },
    total=False,
)



class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilter'],
    },
    total=False,
)



class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilter'],
    },
    total=False,
)



class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# Restaurant types

class RestaurantOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Restaurant create method"""
    id: _int
    location: Optional[_str]
    floors: 'FloorCreateManyNestedWithoutRelationsInput'


class RestaurantCreateInput(RestaurantOptionalCreateInput):
    """Required arguments to the Restaurant create method"""
    name: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class RestaurantOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Restaurant create method, without relations"""
    id: _int
    location: Optional[_str]


class RestaurantCreateWithoutRelationsInput(RestaurantOptionalCreateWithoutRelationsInput):
    """Required arguments to the Restaurant create method, without relations"""
    name: _str

class RestaurantConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'RestaurantCreateWithoutRelationsInput'
    where: 'RestaurantWhereUniqueInput'

class RestaurantCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'RestaurantCreateWithoutRelationsInput'
    connect: 'RestaurantWhereUniqueInput'
    connect_or_create: 'RestaurantConnectOrCreateWithoutRelationsInput'


class RestaurantCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['RestaurantCreateWithoutRelationsInput', List['RestaurantCreateWithoutRelationsInput']]
    connect: Union['RestaurantWhereUniqueInput', List['RestaurantWhereUniqueInput']]
    connect_or_create: Union['RestaurantConnectOrCreateWithoutRelationsInput', List['RestaurantConnectOrCreateWithoutRelationsInput']]

_RestaurantWhereUnique_id_Input = TypedDict(
    '_RestaurantWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

RestaurantWhereUniqueInput = _RestaurantWhereUnique_id_Input


class RestaurantUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    name: _str
    location: Optional[_str]
    floors: 'FloorUpdateManyWithoutRelationsInput'


class RestaurantUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    name: _str
    location: Optional[_str]


class RestaurantUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['RestaurantCreateWithoutRelationsInput']
    connect: List['RestaurantWhereUniqueInput']
    connect_or_create: List['RestaurantConnectOrCreateWithoutRelationsInput']
    set: List['RestaurantWhereUniqueInput']
    disconnect: List['RestaurantWhereUniqueInput']
    delete: List['RestaurantWhereUniqueInput']

    # TODO
    # update: List['RestaurantUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['RestaurantUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['RestaurantScalarWhereInput']
    # upsert: List['RestaurantUpserteWithWhereUniqueWithoutRelationsInput']


class RestaurantUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'RestaurantCreateWithoutRelationsInput'
    connect: 'RestaurantWhereUniqueInput'
    connect_or_create: 'RestaurantConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'RestaurantUpdateInput'
    # upsert: 'RestaurantUpsertWithoutRelationsInput'


class RestaurantUpsertInput(TypedDict):
    create: 'RestaurantCreateInput'
    update: 'RestaurantUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Restaurant_id_OrderByInput = TypedDict(
    '_Restaurant_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Restaurant_name_OrderByInput = TypedDict(
    '_Restaurant_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_Restaurant_location_OrderByInput = TypedDict(
    '_Restaurant_location_OrderByInput',
    {
        'location': 'SortOrder',
    },
    total=True
)

RestaurantOrderByInput = Union[
    '_Restaurant_id_OrderByInput',
    '_Restaurant_name_OrderByInput',
    '_Restaurant_location_OrderByInput',
]



# recursive Restaurant types
# TODO: cleanup these types



RestaurantRelationFilter = TypedDict(
    'RestaurantRelationFilter',
    {
        'is': 'RestaurantWhereInput',
        'is_not': 'RestaurantWhereInput',
    },
    total=False,
)


class RestaurantListRelationFilter(TypedDict, total=False):
    some: 'RestaurantWhereInput'
    none: 'RestaurantWhereInput'
    every: 'RestaurantWhereInput'


class RestaurantInclude(TypedDict, total=False):
    """Restaurant relational arguments"""
    floors: Union[bool, 'FindManyFloorArgsFromRestaurant']


class RestaurantIncludeFromRestaurant(TypedDict, total=False):
    """Relational arguments for Restaurant"""
    floors: Union[bool, 'FindManyFloorArgsFromRestaurant']


class RestaurantArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    include: 'RestaurantIncludeFromRestaurant'


class FindManyRestaurantArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    take: int
    skip: int
    order_by: Union['RestaurantOrderByInput', List['RestaurantOrderByInput']]
    where: 'RestaurantWhereInput'
    cursor: 'RestaurantWhereUniqueInput'
    distinct: List['RestaurantScalarFieldKeys']
    include: 'RestaurantIncludeFromRestaurant'


class FloorIncludeFromRestaurant(TypedDict, total=False):
    """Relational arguments for Restaurant"""
    restaurant: Union[bool, 'RestaurantArgsFromRestaurant']
    tables: Union[bool, 'FindManyTableArgsFromRestaurant']


class FloorArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    include: 'FloorIncludeFromFloor'


class FindManyFloorArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    take: int
    skip: int
    order_by: Union['FloorOrderByInput', List['FloorOrderByInput']]
    where: 'FloorWhereInput'
    cursor: 'FloorWhereUniqueInput'
    distinct: List['FloorScalarFieldKeys']
    include: 'FloorIncludeFromFloor'


class TableIncludeFromRestaurant(TypedDict, total=False):
    """Relational arguments for Restaurant"""
    floor: Union[bool, 'FloorArgsFromRestaurant']
    reservations: Union[bool, 'FindManyReservationArgsFromRestaurant']


class TableArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    include: 'TableIncludeFromTable'


class FindManyTableArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    take: int
    skip: int
    order_by: Union['TableOrderByInput', List['TableOrderByInput']]
    where: 'TableWhereInput'
    cursor: 'TableWhereUniqueInput'
    distinct: List['TableScalarFieldKeys']
    include: 'TableIncludeFromTable'


class MemberIncludeFromRestaurant(TypedDict, total=False):
    """Relational arguments for Restaurant"""
    reservations: Union[bool, 'FindManyReservationArgsFromRestaurant']


class MemberArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    include: 'MemberIncludeFromMember'


class FindManyMemberArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    take: int
    skip: int
    order_by: Union['MemberOrderByInput', List['MemberOrderByInput']]
    where: 'MemberWhereInput'
    cursor: 'MemberWhereUniqueInput'
    distinct: List['MemberScalarFieldKeys']
    include: 'MemberIncludeFromMember'


class ReservationIncludeFromRestaurant(TypedDict, total=False):
    """Relational arguments for Restaurant"""
    table: Union[bool, 'TableArgsFromRestaurant']
    member: Union[bool, 'MemberArgsFromRestaurant']


class ReservationArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    include: 'ReservationIncludeFromReservation'


class FindManyReservationArgsFromRestaurant(TypedDict, total=False):
    """Arguments for Restaurant"""
    take: int
    skip: int
    order_by: Union['ReservationOrderByInput', List['ReservationOrderByInput']]
    where: 'ReservationWhereInput'
    cursor: 'ReservationWhereUniqueInput'
    distinct: List['ReservationScalarFieldKeys']
    include: 'ReservationIncludeFromReservation'




FindManyRestaurantArgs = FindManyRestaurantArgsFromRestaurant
FindFirstRestaurantArgs = FindManyRestaurantArgsFromRestaurant


class RestaurantWhereInput(TypedDict, total=False):
    """Restaurant arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    location: Union[None, _str, 'types.StringFilter']
    floors: 'FloorListRelationFilter'

    # should be noted that AND and NOT should be Union['RestaurantWhereInput', List['RestaurantWhereInput']]
    # but this causes mypy to hang :/
    AND: List['RestaurantWhereInput']
    OR: List['RestaurantWhereInput']
    NOT: List['RestaurantWhereInput']



# aggregate Restaurant types


class RestaurantScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Restaurant arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    location: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['RestaurantScalarWhereWithAggregatesInput']
    OR: List['RestaurantScalarWhereWithAggregatesInput']
    NOT: List['RestaurantScalarWhereWithAggregatesInput']



class RestaurantGroupByOutput(TypedDict, total=False):
    id: _int
    name: _str
    location: _str
    _sum: 'RestaurantSumAggregateOutput'
    _avg: 'RestaurantAvgAggregateOutput'
    _min: 'RestaurantMinAggregateOutput'
    _max: 'RestaurantMaxAggregateOutput'
    _count: 'RestaurantCountAggregateOutput'


class RestaurantAvgAggregateOutput(TypedDict, total=False):
    """Restaurant output for aggregating averages"""
    id: float


class RestaurantSumAggregateOutput(TypedDict, total=False):
    """Restaurant output for aggregating sums"""
    id: _int


class RestaurantScalarAggregateOutput(TypedDict, total=False):
    """Restaurant output including scalar fields"""
    id: _int
    name: _str
    location: _str


RestaurantMinAggregateOutput = RestaurantScalarAggregateOutput
RestaurantMaxAggregateOutput = RestaurantScalarAggregateOutput


class RestaurantMaxAggregateInput(TypedDict, total=False):
    """Restaurant input for aggregating by max"""
    id: bool
    name: bool
    location: bool


class RestaurantMinAggregateInput(TypedDict, total=False):
    """Restaurant input for aggregating by min"""
    id: bool
    name: bool
    location: bool


class RestaurantNumberAggregateInput(TypedDict, total=False):
    """Restaurant input for aggregating numbers"""
    id: bool


RestaurantAvgAggregateInput = RestaurantNumberAggregateInput
RestaurantSumAggregateInput = RestaurantNumberAggregateInput


RestaurantCountAggregateInput = TypedDict(
    'RestaurantCountAggregateInput',
    {
        'id': bool,
        'name': bool,
        'location': bool,
        '_all': bool,
    },
    total=False,
)

RestaurantCountAggregateOutput = TypedDict(
    'RestaurantCountAggregateOutput',
    {
        'id': int,
        'name': int,
        'location': int,
        '_all': int,
    },
    total=False,
)


RestaurantKeys = Literal[
    'id',
    'name',
    'location',
    'floors',
]
RestaurantScalarFieldKeys = Literal[
    'id',
    'name',
    'location',
]
RestaurantScalarFieldKeysT = TypeVar('RestaurantScalarFieldKeysT', bound=RestaurantScalarFieldKeys)

RestaurantRelationalFieldKeys = Literal[
        'floors',
    ]

# Floor types

class FloorOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Floor create method"""
    id: _int
    name: Optional[_str]
    restaurantId: _int
    restaurant: 'RestaurantCreateNestedWithoutRelationsInput'
    tables: 'TableCreateManyNestedWithoutRelationsInput'


class FloorCreateInput(FloorOptionalCreateInput):
    """Required arguments to the Floor create method"""


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class FloorOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Floor create method, without relations"""
    id: _int
    name: Optional[_str]
    restaurantId: _int


class FloorCreateWithoutRelationsInput(FloorOptionalCreateWithoutRelationsInput):
    """Required arguments to the Floor create method, without relations"""

class FloorConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'FloorCreateWithoutRelationsInput'
    where: 'FloorWhereUniqueInput'

class FloorCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'FloorCreateWithoutRelationsInput'
    connect: 'FloorWhereUniqueInput'
    connect_or_create: 'FloorConnectOrCreateWithoutRelationsInput'


class FloorCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['FloorCreateWithoutRelationsInput', List['FloorCreateWithoutRelationsInput']]
    connect: Union['FloorWhereUniqueInput', List['FloorWhereUniqueInput']]
    connect_or_create: Union['FloorConnectOrCreateWithoutRelationsInput', List['FloorConnectOrCreateWithoutRelationsInput']]

_FloorWhereUnique_id_Input = TypedDict(
    '_FloorWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

FloorWhereUniqueInput = _FloorWhereUnique_id_Input


class FloorUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    name: Optional[_str]
    restaurant: 'RestaurantUpdateOneWithoutRelationsInput'
    tables: 'TableUpdateManyWithoutRelationsInput'


class FloorUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    name: Optional[_str]


class FloorUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['FloorCreateWithoutRelationsInput']
    connect: List['FloorWhereUniqueInput']
    connect_or_create: List['FloorConnectOrCreateWithoutRelationsInput']
    set: List['FloorWhereUniqueInput']
    disconnect: List['FloorWhereUniqueInput']
    delete: List['FloorWhereUniqueInput']

    # TODO
    # update: List['FloorUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['FloorUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['FloorScalarWhereInput']
    # upsert: List['FloorUpserteWithWhereUniqueWithoutRelationsInput']


class FloorUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'FloorCreateWithoutRelationsInput'
    connect: 'FloorWhereUniqueInput'
    connect_or_create: 'FloorConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'FloorUpdateInput'
    # upsert: 'FloorUpsertWithoutRelationsInput'


class FloorUpsertInput(TypedDict):
    create: 'FloorCreateInput'
    update: 'FloorUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Floor_id_OrderByInput = TypedDict(
    '_Floor_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Floor_name_OrderByInput = TypedDict(
    '_Floor_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_Floor_restaurantId_OrderByInput = TypedDict(
    '_Floor_restaurantId_OrderByInput',
    {
        'restaurantId': 'SortOrder',
    },
    total=True
)

FloorOrderByInput = Union[
    '_Floor_id_OrderByInput',
    '_Floor_name_OrderByInput',
    '_Floor_restaurantId_OrderByInput',
]



# recursive Floor types
# TODO: cleanup these types



FloorRelationFilter = TypedDict(
    'FloorRelationFilter',
    {
        'is': 'FloorWhereInput',
        'is_not': 'FloorWhereInput',
    },
    total=False,
)


class FloorListRelationFilter(TypedDict, total=False):
    some: 'FloorWhereInput'
    none: 'FloorWhereInput'
    every: 'FloorWhereInput'


class FloorInclude(TypedDict, total=False):
    """Floor relational arguments"""
    restaurant: Union[bool, 'RestaurantArgsFromFloor']
    tables: Union[bool, 'FindManyTableArgsFromFloor']


class RestaurantIncludeFromFloor(TypedDict, total=False):
    """Relational arguments for Floor"""
    floors: Union[bool, 'FindManyFloorArgsFromFloor']


class RestaurantArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    include: 'RestaurantIncludeFromRestaurant'


class FindManyRestaurantArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    take: int
    skip: int
    order_by: Union['RestaurantOrderByInput', List['RestaurantOrderByInput']]
    where: 'RestaurantWhereInput'
    cursor: 'RestaurantWhereUniqueInput'
    distinct: List['RestaurantScalarFieldKeys']
    include: 'RestaurantIncludeFromRestaurant'


class FloorIncludeFromFloor(TypedDict, total=False):
    """Relational arguments for Floor"""
    restaurant: Union[bool, 'RestaurantArgsFromFloor']
    tables: Union[bool, 'FindManyTableArgsFromFloor']


class FloorArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    include: 'FloorIncludeFromFloor'


class FindManyFloorArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    take: int
    skip: int
    order_by: Union['FloorOrderByInput', List['FloorOrderByInput']]
    where: 'FloorWhereInput'
    cursor: 'FloorWhereUniqueInput'
    distinct: List['FloorScalarFieldKeys']
    include: 'FloorIncludeFromFloor'


class TableIncludeFromFloor(TypedDict, total=False):
    """Relational arguments for Floor"""
    floor: Union[bool, 'FloorArgsFromFloor']
    reservations: Union[bool, 'FindManyReservationArgsFromFloor']


class TableArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    include: 'TableIncludeFromTable'


class FindManyTableArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    take: int
    skip: int
    order_by: Union['TableOrderByInput', List['TableOrderByInput']]
    where: 'TableWhereInput'
    cursor: 'TableWhereUniqueInput'
    distinct: List['TableScalarFieldKeys']
    include: 'TableIncludeFromTable'


class MemberIncludeFromFloor(TypedDict, total=False):
    """Relational arguments for Floor"""
    reservations: Union[bool, 'FindManyReservationArgsFromFloor']


class MemberArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    include: 'MemberIncludeFromMember'


class FindManyMemberArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    take: int
    skip: int
    order_by: Union['MemberOrderByInput', List['MemberOrderByInput']]
    where: 'MemberWhereInput'
    cursor: 'MemberWhereUniqueInput'
    distinct: List['MemberScalarFieldKeys']
    include: 'MemberIncludeFromMember'


class ReservationIncludeFromFloor(TypedDict, total=False):
    """Relational arguments for Floor"""
    table: Union[bool, 'TableArgsFromFloor']
    member: Union[bool, 'MemberArgsFromFloor']


class ReservationArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    include: 'ReservationIncludeFromReservation'


class FindManyReservationArgsFromFloor(TypedDict, total=False):
    """Arguments for Floor"""
    take: int
    skip: int
    order_by: Union['ReservationOrderByInput', List['ReservationOrderByInput']]
    where: 'ReservationWhereInput'
    cursor: 'ReservationWhereUniqueInput'
    distinct: List['ReservationScalarFieldKeys']
    include: 'ReservationIncludeFromReservation'




FindManyFloorArgs = FindManyFloorArgsFromFloor
FindFirstFloorArgs = FindManyFloorArgsFromFloor


class FloorWhereInput(TypedDict, total=False):
    """Floor arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[None, _str, 'types.StringFilter']
    restaurantId: Union[_int, 'types.IntFilter']
    restaurant: 'RestaurantRelationFilter'
    tables: 'TableListRelationFilter'

    # should be noted that AND and NOT should be Union['FloorWhereInput', List['FloorWhereInput']]
    # but this causes mypy to hang :/
    AND: List['FloorWhereInput']
    OR: List['FloorWhereInput']
    NOT: List['FloorWhereInput']



# aggregate Floor types


class FloorScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Floor arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    restaurantId: Union[_int, 'types.IntWithAggregatesFilter']

    AND: List['FloorScalarWhereWithAggregatesInput']
    OR: List['FloorScalarWhereWithAggregatesInput']
    NOT: List['FloorScalarWhereWithAggregatesInput']



class FloorGroupByOutput(TypedDict, total=False):
    id: _int
    name: _str
    restaurantId: _int
    _sum: 'FloorSumAggregateOutput'
    _avg: 'FloorAvgAggregateOutput'
    _min: 'FloorMinAggregateOutput'
    _max: 'FloorMaxAggregateOutput'
    _count: 'FloorCountAggregateOutput'


class FloorAvgAggregateOutput(TypedDict, total=False):
    """Floor output for aggregating averages"""
    id: float
    restaurantId: float


class FloorSumAggregateOutput(TypedDict, total=False):
    """Floor output for aggregating sums"""
    id: _int
    restaurantId: _int


class FloorScalarAggregateOutput(TypedDict, total=False):
    """Floor output including scalar fields"""
    id: _int
    name: _str
    restaurantId: _int


FloorMinAggregateOutput = FloorScalarAggregateOutput
FloorMaxAggregateOutput = FloorScalarAggregateOutput


class FloorMaxAggregateInput(TypedDict, total=False):
    """Floor input for aggregating by max"""
    id: bool
    name: bool
    restaurantId: bool


class FloorMinAggregateInput(TypedDict, total=False):
    """Floor input for aggregating by min"""
    id: bool
    name: bool
    restaurantId: bool


class FloorNumberAggregateInput(TypedDict, total=False):
    """Floor input for aggregating numbers"""
    id: bool
    restaurantId: bool


FloorAvgAggregateInput = FloorNumberAggregateInput
FloorSumAggregateInput = FloorNumberAggregateInput


FloorCountAggregateInput = TypedDict(
    'FloorCountAggregateInput',
    {
        'id': bool,
        'name': bool,
        'restaurantId': bool,
        '_all': bool,
    },
    total=False,
)

FloorCountAggregateOutput = TypedDict(
    'FloorCountAggregateOutput',
    {
        'id': int,
        'name': int,
        'restaurantId': int,
        '_all': int,
    },
    total=False,
)


FloorKeys = Literal[
    'id',
    'name',
    'restaurantId',
    'restaurant',
    'tables',
]
FloorScalarFieldKeys = Literal[
    'id',
    'name',
    'restaurantId',
]
FloorScalarFieldKeysT = TypeVar('FloorScalarFieldKeysT', bound=FloorScalarFieldKeys)

FloorRelationalFieldKeys = Literal[
        'restaurant',
        'tables',
    ]

# Table types

class TableOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Table create method"""
    id: _int
    floorId: Optional[_int]
    floor: 'FloorCreateNestedWithoutRelationsInput'
    capacity: Optional[_int]
    posX: Optional[_int]
    posY: Optional[_int]
    width: Optional[_int]
    height: Optional[_int]
    rotation: Optional[_int]
    label: Optional[_str]
    area: Optional[_str]
    reservations: 'ReservationCreateManyNestedWithoutRelationsInput'


class TableCreateInput(TableOptionalCreateInput):
    """Required arguments to the Table create method"""
    number: _int


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class TableOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Table create method, without relations"""
    id: _int
    floorId: Optional[_int]
    capacity: Optional[_int]
    posX: Optional[_int]
    posY: Optional[_int]
    width: Optional[_int]
    height: Optional[_int]
    rotation: Optional[_int]
    label: Optional[_str]
    area: Optional[_str]


class TableCreateWithoutRelationsInput(TableOptionalCreateWithoutRelationsInput):
    """Required arguments to the Table create method, without relations"""
    number: _int

class TableConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'TableCreateWithoutRelationsInput'
    where: 'TableWhereUniqueInput'

class TableCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'TableCreateWithoutRelationsInput'
    connect: 'TableWhereUniqueInput'
    connect_or_create: 'TableConnectOrCreateWithoutRelationsInput'


class TableCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['TableCreateWithoutRelationsInput', List['TableCreateWithoutRelationsInput']]
    connect: Union['TableWhereUniqueInput', List['TableWhereUniqueInput']]
    connect_or_create: Union['TableConnectOrCreateWithoutRelationsInput', List['TableConnectOrCreateWithoutRelationsInput']]

_TableWhereUnique_id_Input = TypedDict(
    '_TableWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

TableWhereUniqueInput = _TableWhereUnique_id_Input


class TableUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    number: Union[AtomicIntInput, _int]
    floor: 'FloorUpdateOneWithoutRelationsInput'
    capacity: Optional[Union[AtomicIntInput, _int]]
    posX: Optional[Union[AtomicIntInput, _int]]
    posY: Optional[Union[AtomicIntInput, _int]]
    width: Optional[Union[AtomicIntInput, _int]]
    height: Optional[Union[AtomicIntInput, _int]]
    rotation: Optional[Union[AtomicIntInput, _int]]
    label: Optional[_str]
    area: Optional[_str]
    reservations: 'ReservationUpdateManyWithoutRelationsInput'


class TableUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    number: Union[AtomicIntInput, _int]
    capacity: Optional[Union[AtomicIntInput, _int]]
    posX: Optional[Union[AtomicIntInput, _int]]
    posY: Optional[Union[AtomicIntInput, _int]]
    width: Optional[Union[AtomicIntInput, _int]]
    height: Optional[Union[AtomicIntInput, _int]]
    rotation: Optional[Union[AtomicIntInput, _int]]
    label: Optional[_str]
    area: Optional[_str]


class TableUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['TableCreateWithoutRelationsInput']
    connect: List['TableWhereUniqueInput']
    connect_or_create: List['TableConnectOrCreateWithoutRelationsInput']
    set: List['TableWhereUniqueInput']
    disconnect: List['TableWhereUniqueInput']
    delete: List['TableWhereUniqueInput']

    # TODO
    # update: List['TableUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['TableUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['TableScalarWhereInput']
    # upsert: List['TableUpserteWithWhereUniqueWithoutRelationsInput']


class TableUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'TableCreateWithoutRelationsInput'
    connect: 'TableWhereUniqueInput'
    connect_or_create: 'TableConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'TableUpdateInput'
    # upsert: 'TableUpsertWithoutRelationsInput'


class TableUpsertInput(TypedDict):
    create: 'TableCreateInput'
    update: 'TableUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Table_id_OrderByInput = TypedDict(
    '_Table_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Table_number_OrderByInput = TypedDict(
    '_Table_number_OrderByInput',
    {
        'number': 'SortOrder',
    },
    total=True
)

_Table_floorId_OrderByInput = TypedDict(
    '_Table_floorId_OrderByInput',
    {
        'floorId': 'SortOrder',
    },
    total=True
)

_Table_capacity_OrderByInput = TypedDict(
    '_Table_capacity_OrderByInput',
    {
        'capacity': 'SortOrder',
    },
    total=True
)

_Table_posX_OrderByInput = TypedDict(
    '_Table_posX_OrderByInput',
    {
        'posX': 'SortOrder',
    },
    total=True
)

_Table_posY_OrderByInput = TypedDict(
    '_Table_posY_OrderByInput',
    {
        'posY': 'SortOrder',
    },
    total=True
)

_Table_width_OrderByInput = TypedDict(
    '_Table_width_OrderByInput',
    {
        'width': 'SortOrder',
    },
    total=True
)

_Table_height_OrderByInput = TypedDict(
    '_Table_height_OrderByInput',
    {
        'height': 'SortOrder',
    },
    total=True
)

_Table_rotation_OrderByInput = TypedDict(
    '_Table_rotation_OrderByInput',
    {
        'rotation': 'SortOrder',
    },
    total=True
)

_Table_label_OrderByInput = TypedDict(
    '_Table_label_OrderByInput',
    {
        'label': 'SortOrder',
    },
    total=True
)

_Table_area_OrderByInput = TypedDict(
    '_Table_area_OrderByInput',
    {
        'area': 'SortOrder',
    },
    total=True
)

TableOrderByInput = Union[
    '_Table_id_OrderByInput',
    '_Table_number_OrderByInput',
    '_Table_floorId_OrderByInput',
    '_Table_capacity_OrderByInput',
    '_Table_posX_OrderByInput',
    '_Table_posY_OrderByInput',
    '_Table_width_OrderByInput',
    '_Table_height_OrderByInput',
    '_Table_rotation_OrderByInput',
    '_Table_label_OrderByInput',
    '_Table_area_OrderByInput',
]



# recursive Table types
# TODO: cleanup these types



TableRelationFilter = TypedDict(
    'TableRelationFilter',
    {
        'is': 'TableWhereInput',
        'is_not': 'TableWhereInput',
    },
    total=False,
)


class TableListRelationFilter(TypedDict, total=False):
    some: 'TableWhereInput'
    none: 'TableWhereInput'
    every: 'TableWhereInput'


class TableInclude(TypedDict, total=False):
    """Table relational arguments"""
    floor: Union[bool, 'FloorArgsFromTable']
    reservations: Union[bool, 'FindManyReservationArgsFromTable']


class RestaurantIncludeFromTable(TypedDict, total=False):
    """Relational arguments for Table"""
    floors: Union[bool, 'FindManyFloorArgsFromTable']


class RestaurantArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    include: 'RestaurantIncludeFromRestaurant'


class FindManyRestaurantArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    take: int
    skip: int
    order_by: Union['RestaurantOrderByInput', List['RestaurantOrderByInput']]
    where: 'RestaurantWhereInput'
    cursor: 'RestaurantWhereUniqueInput'
    distinct: List['RestaurantScalarFieldKeys']
    include: 'RestaurantIncludeFromRestaurant'


class FloorIncludeFromTable(TypedDict, total=False):
    """Relational arguments for Table"""
    restaurant: Union[bool, 'RestaurantArgsFromTable']
    tables: Union[bool, 'FindManyTableArgsFromTable']


class FloorArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    include: 'FloorIncludeFromFloor'


class FindManyFloorArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    take: int
    skip: int
    order_by: Union['FloorOrderByInput', List['FloorOrderByInput']]
    where: 'FloorWhereInput'
    cursor: 'FloorWhereUniqueInput'
    distinct: List['FloorScalarFieldKeys']
    include: 'FloorIncludeFromFloor'


class TableIncludeFromTable(TypedDict, total=False):
    """Relational arguments for Table"""
    floor: Union[bool, 'FloorArgsFromTable']
    reservations: Union[bool, 'FindManyReservationArgsFromTable']


class TableArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    include: 'TableIncludeFromTable'


class FindManyTableArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    take: int
    skip: int
    order_by: Union['TableOrderByInput', List['TableOrderByInput']]
    where: 'TableWhereInput'
    cursor: 'TableWhereUniqueInput'
    distinct: List['TableScalarFieldKeys']
    include: 'TableIncludeFromTable'


class MemberIncludeFromTable(TypedDict, total=False):
    """Relational arguments for Table"""
    reservations: Union[bool, 'FindManyReservationArgsFromTable']


class MemberArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    include: 'MemberIncludeFromMember'


class FindManyMemberArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    take: int
    skip: int
    order_by: Union['MemberOrderByInput', List['MemberOrderByInput']]
    where: 'MemberWhereInput'
    cursor: 'MemberWhereUniqueInput'
    distinct: List['MemberScalarFieldKeys']
    include: 'MemberIncludeFromMember'


class ReservationIncludeFromTable(TypedDict, total=False):
    """Relational arguments for Table"""
    table: Union[bool, 'TableArgsFromTable']
    member: Union[bool, 'MemberArgsFromTable']


class ReservationArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    include: 'ReservationIncludeFromReservation'


class FindManyReservationArgsFromTable(TypedDict, total=False):
    """Arguments for Table"""
    take: int
    skip: int
    order_by: Union['ReservationOrderByInput', List['ReservationOrderByInput']]
    where: 'ReservationWhereInput'
    cursor: 'ReservationWhereUniqueInput'
    distinct: List['ReservationScalarFieldKeys']
    include: 'ReservationIncludeFromReservation'




FindManyTableArgs = FindManyTableArgsFromTable
FindFirstTableArgs = FindManyTableArgsFromTable


class TableWhereInput(TypedDict, total=False):
    """Table arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    number: Union[_int, 'types.IntFilter']
    floorId: Union[None, _int, 'types.IntFilter']
    floor: 'FloorRelationFilter'
    capacity: Union[None, _int, 'types.IntFilter']
    posX: Union[None, _int, 'types.IntFilter']
    posY: Union[None, _int, 'types.IntFilter']
    width: Union[None, _int, 'types.IntFilter']
    height: Union[None, _int, 'types.IntFilter']
    rotation: Union[None, _int, 'types.IntFilter']
    label: Union[None, _str, 'types.StringFilter']
    area: Union[None, _str, 'types.StringFilter']
    reservations: 'ReservationListRelationFilter'

    # should be noted that AND and NOT should be Union['TableWhereInput', List['TableWhereInput']]
    # but this causes mypy to hang :/
    AND: List['TableWhereInput']
    OR: List['TableWhereInput']
    NOT: List['TableWhereInput']



# aggregate Table types


class TableScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Table arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    number: Union[_int, 'types.IntWithAggregatesFilter']
    floorId: Union[_int, 'types.IntWithAggregatesFilter']
    capacity: Union[_int, 'types.IntWithAggregatesFilter']
    posX: Union[_int, 'types.IntWithAggregatesFilter']
    posY: Union[_int, 'types.IntWithAggregatesFilter']
    width: Union[_int, 'types.IntWithAggregatesFilter']
    height: Union[_int, 'types.IntWithAggregatesFilter']
    rotation: Union[_int, 'types.IntWithAggregatesFilter']
    label: Union[_str, 'types.StringWithAggregatesFilter']
    area: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['TableScalarWhereWithAggregatesInput']
    OR: List['TableScalarWhereWithAggregatesInput']
    NOT: List['TableScalarWhereWithAggregatesInput']



class TableGroupByOutput(TypedDict, total=False):
    id: _int
    number: _int
    floorId: _int
    capacity: _int
    posX: _int
    posY: _int
    width: _int
    height: _int
    rotation: _int
    label: _str
    area: _str
    _sum: 'TableSumAggregateOutput'
    _avg: 'TableAvgAggregateOutput'
    _min: 'TableMinAggregateOutput'
    _max: 'TableMaxAggregateOutput'
    _count: 'TableCountAggregateOutput'


class TableAvgAggregateOutput(TypedDict, total=False):
    """Table output for aggregating averages"""
    id: float
    number: float
    floorId: float
    capacity: float
    posX: float
    posY: float
    width: float
    height: float
    rotation: float


class TableSumAggregateOutput(TypedDict, total=False):
    """Table output for aggregating sums"""
    id: _int
    number: _int
    floorId: _int
    capacity: _int
    posX: _int
    posY: _int
    width: _int
    height: _int
    rotation: _int


class TableScalarAggregateOutput(TypedDict, total=False):
    """Table output including scalar fields"""
    id: _int
    number: _int
    floorId: _int
    capacity: _int
    posX: _int
    posY: _int
    width: _int
    height: _int
    rotation: _int
    label: _str
    area: _str


TableMinAggregateOutput = TableScalarAggregateOutput
TableMaxAggregateOutput = TableScalarAggregateOutput


class TableMaxAggregateInput(TypedDict, total=False):
    """Table input for aggregating by max"""
    id: bool
    number: bool
    floorId: bool
    capacity: bool
    posX: bool
    posY: bool
    width: bool
    height: bool
    rotation: bool
    label: bool
    area: bool


class TableMinAggregateInput(TypedDict, total=False):
    """Table input for aggregating by min"""
    id: bool
    number: bool
    floorId: bool
    capacity: bool
    posX: bool
    posY: bool
    width: bool
    height: bool
    rotation: bool
    label: bool
    area: bool


class TableNumberAggregateInput(TypedDict, total=False):
    """Table input for aggregating numbers"""
    id: bool
    number: bool
    floorId: bool
    capacity: bool
    posX: bool
    posY: bool
    width: bool
    height: bool
    rotation: bool


TableAvgAggregateInput = TableNumberAggregateInput
TableSumAggregateInput = TableNumberAggregateInput


TableCountAggregateInput = TypedDict(
    'TableCountAggregateInput',
    {
        'id': bool,
        'number': bool,
        'floorId': bool,
        'capacity': bool,
        'posX': bool,
        'posY': bool,
        'width': bool,
        'height': bool,
        'rotation': bool,
        'label': bool,
        'area': bool,
        '_all': bool,
    },
    total=False,
)

TableCountAggregateOutput = TypedDict(
    'TableCountAggregateOutput',
    {
        'id': int,
        'number': int,
        'floorId': int,
        'capacity': int,
        'posX': int,
        'posY': int,
        'width': int,
        'height': int,
        'rotation': int,
        'label': int,
        'area': int,
        '_all': int,
    },
    total=False,
)


TableKeys = Literal[
    'id',
    'number',
    'floorId',
    'floor',
    'capacity',
    'posX',
    'posY',
    'width',
    'height',
    'rotation',
    'label',
    'area',
    'reservations',
]
TableScalarFieldKeys = Literal[
    'id',
    'number',
    'floorId',
    'capacity',
    'posX',
    'posY',
    'width',
    'height',
    'rotation',
    'label',
    'area',
]
TableScalarFieldKeysT = TypeVar('TableScalarFieldKeysT', bound=TableScalarFieldKeys)

TableRelationalFieldKeys = Literal[
        'floor',
        'reservations',
    ]

# Member types

class MemberOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Member create method"""
    id: _int
    phone: Optional[_str]
    reservations: 'ReservationCreateManyNestedWithoutRelationsInput'


class MemberCreateInput(MemberOptionalCreateInput):
    """Required arguments to the Member create method"""
    name: _str
    email: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class MemberOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Member create method, without relations"""
    id: _int
    phone: Optional[_str]


class MemberCreateWithoutRelationsInput(MemberOptionalCreateWithoutRelationsInput):
    """Required arguments to the Member create method, without relations"""
    name: _str
    email: _str

class MemberConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'MemberCreateWithoutRelationsInput'
    where: 'MemberWhereUniqueInput'

class MemberCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'MemberCreateWithoutRelationsInput'
    connect: 'MemberWhereUniqueInput'
    connect_or_create: 'MemberConnectOrCreateWithoutRelationsInput'


class MemberCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['MemberCreateWithoutRelationsInput', List['MemberCreateWithoutRelationsInput']]
    connect: Union['MemberWhereUniqueInput', List['MemberWhereUniqueInput']]
    connect_or_create: Union['MemberConnectOrCreateWithoutRelationsInput', List['MemberConnectOrCreateWithoutRelationsInput']]

_MemberWhereUnique_id_Input = TypedDict(
    '_MemberWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

_MemberWhereUnique_email_Input = TypedDict(
    '_MemberWhereUnique_email_Input',
    {
        'email': '_str',
    },
    total=True
)

MemberWhereUniqueInput = Union[
    '_MemberWhereUnique_id_Input',
    '_MemberWhereUnique_email_Input',
]


class MemberUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    name: _str
    email: _str
    phone: Optional[_str]
    reservations: 'ReservationUpdateManyWithoutRelationsInput'


class MemberUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    name: _str
    email: _str
    phone: Optional[_str]


class MemberUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['MemberCreateWithoutRelationsInput']
    connect: List['MemberWhereUniqueInput']
    connect_or_create: List['MemberConnectOrCreateWithoutRelationsInput']
    set: List['MemberWhereUniqueInput']
    disconnect: List['MemberWhereUniqueInput']
    delete: List['MemberWhereUniqueInput']

    # TODO
    # update: List['MemberUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['MemberUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['MemberScalarWhereInput']
    # upsert: List['MemberUpserteWithWhereUniqueWithoutRelationsInput']


class MemberUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'MemberCreateWithoutRelationsInput'
    connect: 'MemberWhereUniqueInput'
    connect_or_create: 'MemberConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'MemberUpdateInput'
    # upsert: 'MemberUpsertWithoutRelationsInput'


class MemberUpsertInput(TypedDict):
    create: 'MemberCreateInput'
    update: 'MemberUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Member_id_OrderByInput = TypedDict(
    '_Member_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Member_name_OrderByInput = TypedDict(
    '_Member_name_OrderByInput',
    {
        'name': 'SortOrder',
    },
    total=True
)

_Member_email_OrderByInput = TypedDict(
    '_Member_email_OrderByInput',
    {
        'email': 'SortOrder',
    },
    total=True
)

_Member_phone_OrderByInput = TypedDict(
    '_Member_phone_OrderByInput',
    {
        'phone': 'SortOrder',
    },
    total=True
)

MemberOrderByInput = Union[
    '_Member_id_OrderByInput',
    '_Member_name_OrderByInput',
    '_Member_email_OrderByInput',
    '_Member_phone_OrderByInput',
]



# recursive Member types
# TODO: cleanup these types



MemberRelationFilter = TypedDict(
    'MemberRelationFilter',
    {
        'is': 'MemberWhereInput',
        'is_not': 'MemberWhereInput',
    },
    total=False,
)


class MemberListRelationFilter(TypedDict, total=False):
    some: 'MemberWhereInput'
    none: 'MemberWhereInput'
    every: 'MemberWhereInput'


class MemberInclude(TypedDict, total=False):
    """Member relational arguments"""
    reservations: Union[bool, 'FindManyReservationArgsFromMember']


class RestaurantIncludeFromMember(TypedDict, total=False):
    """Relational arguments for Member"""
    floors: Union[bool, 'FindManyFloorArgsFromMember']


class RestaurantArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    include: 'RestaurantIncludeFromRestaurant'


class FindManyRestaurantArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    take: int
    skip: int
    order_by: Union['RestaurantOrderByInput', List['RestaurantOrderByInput']]
    where: 'RestaurantWhereInput'
    cursor: 'RestaurantWhereUniqueInput'
    distinct: List['RestaurantScalarFieldKeys']
    include: 'RestaurantIncludeFromRestaurant'


class FloorIncludeFromMember(TypedDict, total=False):
    """Relational arguments for Member"""
    restaurant: Union[bool, 'RestaurantArgsFromMember']
    tables: Union[bool, 'FindManyTableArgsFromMember']


class FloorArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    include: 'FloorIncludeFromFloor'


class FindManyFloorArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    take: int
    skip: int
    order_by: Union['FloorOrderByInput', List['FloorOrderByInput']]
    where: 'FloorWhereInput'
    cursor: 'FloorWhereUniqueInput'
    distinct: List['FloorScalarFieldKeys']
    include: 'FloorIncludeFromFloor'


class TableIncludeFromMember(TypedDict, total=False):
    """Relational arguments for Member"""
    floor: Union[bool, 'FloorArgsFromMember']
    reservations: Union[bool, 'FindManyReservationArgsFromMember']


class TableArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    include: 'TableIncludeFromTable'


class FindManyTableArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    take: int
    skip: int
    order_by: Union['TableOrderByInput', List['TableOrderByInput']]
    where: 'TableWhereInput'
    cursor: 'TableWhereUniqueInput'
    distinct: List['TableScalarFieldKeys']
    include: 'TableIncludeFromTable'


class MemberIncludeFromMember(TypedDict, total=False):
    """Relational arguments for Member"""
    reservations: Union[bool, 'FindManyReservationArgsFromMember']


class MemberArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    include: 'MemberIncludeFromMember'


class FindManyMemberArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    take: int
    skip: int
    order_by: Union['MemberOrderByInput', List['MemberOrderByInput']]
    where: 'MemberWhereInput'
    cursor: 'MemberWhereUniqueInput'
    distinct: List['MemberScalarFieldKeys']
    include: 'MemberIncludeFromMember'


class ReservationIncludeFromMember(TypedDict, total=False):
    """Relational arguments for Member"""
    table: Union[bool, 'TableArgsFromMember']
    member: Union[bool, 'MemberArgsFromMember']


class ReservationArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    include: 'ReservationIncludeFromReservation'


class FindManyReservationArgsFromMember(TypedDict, total=False):
    """Arguments for Member"""
    take: int
    skip: int
    order_by: Union['ReservationOrderByInput', List['ReservationOrderByInput']]
    where: 'ReservationWhereInput'
    cursor: 'ReservationWhereUniqueInput'
    distinct: List['ReservationScalarFieldKeys']
    include: 'ReservationIncludeFromReservation'




FindManyMemberArgs = FindManyMemberArgsFromMember
FindFirstMemberArgs = FindManyMemberArgsFromMember


class MemberWhereInput(TypedDict, total=False):
    """Member arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    name: Union[_str, 'types.StringFilter']
    email: Union[_str, 'types.StringFilter']
    phone: Union[None, _str, 'types.StringFilter']
    reservations: 'ReservationListRelationFilter'

    # should be noted that AND and NOT should be Union['MemberWhereInput', List['MemberWhereInput']]
    # but this causes mypy to hang :/
    AND: List['MemberWhereInput']
    OR: List['MemberWhereInput']
    NOT: List['MemberWhereInput']



# aggregate Member types


class MemberScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Member arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    name: Union[_str, 'types.StringWithAggregatesFilter']
    email: Union[_str, 'types.StringWithAggregatesFilter']
    phone: Union[_str, 'types.StringWithAggregatesFilter']

    AND: List['MemberScalarWhereWithAggregatesInput']
    OR: List['MemberScalarWhereWithAggregatesInput']
    NOT: List['MemberScalarWhereWithAggregatesInput']



class MemberGroupByOutput(TypedDict, total=False):
    id: _int
    name: _str
    email: _str
    phone: _str
    _sum: 'MemberSumAggregateOutput'
    _avg: 'MemberAvgAggregateOutput'
    _min: 'MemberMinAggregateOutput'
    _max: 'MemberMaxAggregateOutput'
    _count: 'MemberCountAggregateOutput'


class MemberAvgAggregateOutput(TypedDict, total=False):
    """Member output for aggregating averages"""
    id: float


class MemberSumAggregateOutput(TypedDict, total=False):
    """Member output for aggregating sums"""
    id: _int


class MemberScalarAggregateOutput(TypedDict, total=False):
    """Member output including scalar fields"""
    id: _int
    name: _str
    email: _str
    phone: _str


MemberMinAggregateOutput = MemberScalarAggregateOutput
MemberMaxAggregateOutput = MemberScalarAggregateOutput


class MemberMaxAggregateInput(TypedDict, total=False):
    """Member input for aggregating by max"""
    id: bool
    name: bool
    email: bool
    phone: bool


class MemberMinAggregateInput(TypedDict, total=False):
    """Member input for aggregating by min"""
    id: bool
    name: bool
    email: bool
    phone: bool


class MemberNumberAggregateInput(TypedDict, total=False):
    """Member input for aggregating numbers"""
    id: bool


MemberAvgAggregateInput = MemberNumberAggregateInput
MemberSumAggregateInput = MemberNumberAggregateInput


MemberCountAggregateInput = TypedDict(
    'MemberCountAggregateInput',
    {
        'id': bool,
        'name': bool,
        'email': bool,
        'phone': bool,
        '_all': bool,
    },
    total=False,
)

MemberCountAggregateOutput = TypedDict(
    'MemberCountAggregateOutput',
    {
        'id': int,
        'name': int,
        'email': int,
        'phone': int,
        '_all': int,
    },
    total=False,
)


MemberKeys = Literal[
    'id',
    'name',
    'email',
    'phone',
    'reservations',
]
MemberScalarFieldKeys = Literal[
    'id',
    'name',
    'email',
    'phone',
]
MemberScalarFieldKeysT = TypeVar('MemberScalarFieldKeysT', bound=MemberScalarFieldKeys)

MemberRelationalFieldKeys = Literal[
        'reservations',
    ]

# Reservation types

class ReservationOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the Reservation create method"""
    id: _int
    tableId: _int
    table: 'TableCreateNestedWithoutRelationsInput'
    memberId: _int
    member: 'MemberCreateNestedWithoutRelationsInput'
    status: _str
    partySize: Optional[_int]
    notes: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ReservationCreateInput(ReservationOptionalCreateInput):
    """Required arguments to the Reservation create method"""
    date: datetime.datetime


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class ReservationOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the Reservation create method, without relations"""
    id: _int
    tableId: _int
    memberId: _int
    status: _str
    partySize: Optional[_int]
    notes: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ReservationCreateWithoutRelationsInput(ReservationOptionalCreateWithoutRelationsInput):
    """Required arguments to the Reservation create method, without relations"""
    date: datetime.datetime

class ReservationConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'ReservationCreateWithoutRelationsInput'
    where: 'ReservationWhereUniqueInput'

class ReservationCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'ReservationCreateWithoutRelationsInput'
    connect: 'ReservationWhereUniqueInput'
    connect_or_create: 'ReservationConnectOrCreateWithoutRelationsInput'


class ReservationCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['ReservationCreateWithoutRelationsInput', List['ReservationCreateWithoutRelationsInput']]
    connect: Union['ReservationWhereUniqueInput', List['ReservationWhereUniqueInput']]
    connect_or_create: Union['ReservationConnectOrCreateWithoutRelationsInput', List['ReservationConnectOrCreateWithoutRelationsInput']]

_ReservationWhereUnique_id_Input = TypedDict(
    '_ReservationWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

ReservationWhereUniqueInput = _ReservationWhereUnique_id_Input


class ReservationUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    date: datetime.datetime
    table: 'TableUpdateOneWithoutRelationsInput'
    member: 'MemberUpdateOneWithoutRelationsInput'
    status: _str
    partySize: Optional[Union[AtomicIntInput, _int]]
    notes: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ReservationUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    date: datetime.datetime
    status: _str
    partySize: Optional[Union[AtomicIntInput, _int]]
    notes: Optional[_str]
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


class ReservationUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['ReservationCreateWithoutRelationsInput']
    connect: List['ReservationWhereUniqueInput']
    connect_or_create: List['ReservationConnectOrCreateWithoutRelationsInput']
    set: List['ReservationWhereUniqueInput']
    disconnect: List['ReservationWhereUniqueInput']
    delete: List['ReservationWhereUniqueInput']

    # TODO
    # update: List['ReservationUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['ReservationUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['ReservationScalarWhereInput']
    # upsert: List['ReservationUpserteWithWhereUniqueWithoutRelationsInput']


class ReservationUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'ReservationCreateWithoutRelationsInput'
    connect: 'ReservationWhereUniqueInput'
    connect_or_create: 'ReservationConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'ReservationUpdateInput'
    # upsert: 'ReservationUpsertWithoutRelationsInput'


class ReservationUpsertInput(TypedDict):
    create: 'ReservationCreateInput'
    update: 'ReservationUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_Reservation_id_OrderByInput = TypedDict(
    '_Reservation_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_Reservation_date_OrderByInput = TypedDict(
    '_Reservation_date_OrderByInput',
    {
        'date': 'SortOrder',
    },
    total=True
)

_Reservation_tableId_OrderByInput = TypedDict(
    '_Reservation_tableId_OrderByInput',
    {
        'tableId': 'SortOrder',
    },
    total=True
)

_Reservation_memberId_OrderByInput = TypedDict(
    '_Reservation_memberId_OrderByInput',
    {
        'memberId': 'SortOrder',
    },
    total=True
)

_Reservation_status_OrderByInput = TypedDict(
    '_Reservation_status_OrderByInput',
    {
        'status': 'SortOrder',
    },
    total=True
)

_Reservation_partySize_OrderByInput = TypedDict(
    '_Reservation_partySize_OrderByInput',
    {
        'partySize': 'SortOrder',
    },
    total=True
)

_Reservation_notes_OrderByInput = TypedDict(
    '_Reservation_notes_OrderByInput',
    {
        'notes': 'SortOrder',
    },
    total=True
)

_Reservation_createdAt_OrderByInput = TypedDict(
    '_Reservation_createdAt_OrderByInput',
    {
        'createdAt': 'SortOrder',
    },
    total=True
)

_Reservation_updatedAt_OrderByInput = TypedDict(
    '_Reservation_updatedAt_OrderByInput',
    {
        'updatedAt': 'SortOrder',
    },
    total=True
)

ReservationOrderByInput = Union[
    '_Reservation_id_OrderByInput',
    '_Reservation_date_OrderByInput',
    '_Reservation_tableId_OrderByInput',
    '_Reservation_memberId_OrderByInput',
    '_Reservation_status_OrderByInput',
    '_Reservation_partySize_OrderByInput',
    '_Reservation_notes_OrderByInput',
    '_Reservation_createdAt_OrderByInput',
    '_Reservation_updatedAt_OrderByInput',
]



# recursive Reservation types
# TODO: cleanup these types



ReservationRelationFilter = TypedDict(
    'ReservationRelationFilter',
    {
        'is': 'ReservationWhereInput',
        'is_not': 'ReservationWhereInput',
    },
    total=False,
)


class ReservationListRelationFilter(TypedDict, total=False):
    some: 'ReservationWhereInput'
    none: 'ReservationWhereInput'
    every: 'ReservationWhereInput'


class ReservationInclude(TypedDict, total=False):
    """Reservation relational arguments"""
    table: Union[bool, 'TableArgsFromReservation']
    member: Union[bool, 'MemberArgsFromReservation']


class RestaurantIncludeFromReservation(TypedDict, total=False):
    """Relational arguments for Reservation"""
    floors: Union[bool, 'FindManyFloorArgsFromReservation']


class RestaurantArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    include: 'RestaurantIncludeFromRestaurant'


class FindManyRestaurantArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    take: int
    skip: int
    order_by: Union['RestaurantOrderByInput', List['RestaurantOrderByInput']]
    where: 'RestaurantWhereInput'
    cursor: 'RestaurantWhereUniqueInput'
    distinct: List['RestaurantScalarFieldKeys']
    include: 'RestaurantIncludeFromRestaurant'


class FloorIncludeFromReservation(TypedDict, total=False):
    """Relational arguments for Reservation"""
    restaurant: Union[bool, 'RestaurantArgsFromReservation']
    tables: Union[bool, 'FindManyTableArgsFromReservation']


class FloorArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    include: 'FloorIncludeFromFloor'


class FindManyFloorArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    take: int
    skip: int
    order_by: Union['FloorOrderByInput', List['FloorOrderByInput']]
    where: 'FloorWhereInput'
    cursor: 'FloorWhereUniqueInput'
    distinct: List['FloorScalarFieldKeys']
    include: 'FloorIncludeFromFloor'


class TableIncludeFromReservation(TypedDict, total=False):
    """Relational arguments for Reservation"""
    floor: Union[bool, 'FloorArgsFromReservation']
    reservations: Union[bool, 'FindManyReservationArgsFromReservation']


class TableArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    include: 'TableIncludeFromTable'


class FindManyTableArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    take: int
    skip: int
    order_by: Union['TableOrderByInput', List['TableOrderByInput']]
    where: 'TableWhereInput'
    cursor: 'TableWhereUniqueInput'
    distinct: List['TableScalarFieldKeys']
    include: 'TableIncludeFromTable'


class MemberIncludeFromReservation(TypedDict, total=False):
    """Relational arguments for Reservation"""
    reservations: Union[bool, 'FindManyReservationArgsFromReservation']


class MemberArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    include: 'MemberIncludeFromMember'


class FindManyMemberArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    take: int
    skip: int
    order_by: Union['MemberOrderByInput', List['MemberOrderByInput']]
    where: 'MemberWhereInput'
    cursor: 'MemberWhereUniqueInput'
    distinct: List['MemberScalarFieldKeys']
    include: 'MemberIncludeFromMember'


class ReservationIncludeFromReservation(TypedDict, total=False):
    """Relational arguments for Reservation"""
    table: Union[bool, 'TableArgsFromReservation']
    member: Union[bool, 'MemberArgsFromReservation']


class ReservationArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    include: 'ReservationIncludeFromReservation'


class FindManyReservationArgsFromReservation(TypedDict, total=False):
    """Arguments for Reservation"""
    take: int
    skip: int
    order_by: Union['ReservationOrderByInput', List['ReservationOrderByInput']]
    where: 'ReservationWhereInput'
    cursor: 'ReservationWhereUniqueInput'
    distinct: List['ReservationScalarFieldKeys']
    include: 'ReservationIncludeFromReservation'




FindManyReservationArgs = FindManyReservationArgsFromReservation
FindFirstReservationArgs = FindManyReservationArgsFromReservation


class ReservationWhereInput(TypedDict, total=False):
    """Reservation arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    date: Union[datetime.datetime, 'types.DateTimeFilter']
    tableId: Union[_int, 'types.IntFilter']
    table: 'TableRelationFilter'
    memberId: Union[_int, 'types.IntFilter']
    member: 'MemberRelationFilter'
    status: Union[_str, 'types.StringFilter']
    partySize: Union[None, _int, 'types.IntFilter']
    notes: Union[None, _str, 'types.StringFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['ReservationWhereInput', List['ReservationWhereInput']]
    # but this causes mypy to hang :/
    AND: List['ReservationWhereInput']
    OR: List['ReservationWhereInput']
    NOT: List['ReservationWhereInput']



# aggregate Reservation types


class ReservationScalarWhereWithAggregatesInput(TypedDict, total=False):
    """Reservation arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    date: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    tableId: Union[_int, 'types.IntWithAggregatesFilter']
    memberId: Union[_int, 'types.IntWithAggregatesFilter']
    status: Union[_str, 'types.StringWithAggregatesFilter']
    partySize: Union[_int, 'types.IntWithAggregatesFilter']
    notes: Union[_str, 'types.StringWithAggregatesFilter']
    createdAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    updatedAt: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['ReservationScalarWhereWithAggregatesInput']
    OR: List['ReservationScalarWhereWithAggregatesInput']
    NOT: List['ReservationScalarWhereWithAggregatesInput']



class ReservationGroupByOutput(TypedDict, total=False):
    id: _int
    date: datetime.datetime
    tableId: _int
    memberId: _int
    status: _str
    partySize: _int
    notes: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime
    _sum: 'ReservationSumAggregateOutput'
    _avg: 'ReservationAvgAggregateOutput'
    _min: 'ReservationMinAggregateOutput'
    _max: 'ReservationMaxAggregateOutput'
    _count: 'ReservationCountAggregateOutput'


class ReservationAvgAggregateOutput(TypedDict, total=False):
    """Reservation output for aggregating averages"""
    id: float
    tableId: float
    memberId: float
    partySize: float


class ReservationSumAggregateOutput(TypedDict, total=False):
    """Reservation output for aggregating sums"""
    id: _int
    tableId: _int
    memberId: _int
    partySize: _int


class ReservationScalarAggregateOutput(TypedDict, total=False):
    """Reservation output including scalar fields"""
    id: _int
    date: datetime.datetime
    tableId: _int
    memberId: _int
    status: _str
    partySize: _int
    notes: _str
    createdAt: datetime.datetime
    updatedAt: datetime.datetime


ReservationMinAggregateOutput = ReservationScalarAggregateOutput
ReservationMaxAggregateOutput = ReservationScalarAggregateOutput


class ReservationMaxAggregateInput(TypedDict, total=False):
    """Reservation input for aggregating by max"""
    id: bool
    date: bool
    tableId: bool
    memberId: bool
    status: bool
    partySize: bool
    notes: bool
    createdAt: bool
    updatedAt: bool


class ReservationMinAggregateInput(TypedDict, total=False):
    """Reservation input for aggregating by min"""
    id: bool
    date: bool
    tableId: bool
    memberId: bool
    status: bool
    partySize: bool
    notes: bool
    createdAt: bool
    updatedAt: bool


class ReservationNumberAggregateInput(TypedDict, total=False):
    """Reservation input for aggregating numbers"""
    id: bool
    tableId: bool
    memberId: bool
    partySize: bool


ReservationAvgAggregateInput = ReservationNumberAggregateInput
ReservationSumAggregateInput = ReservationNumberAggregateInput


ReservationCountAggregateInput = TypedDict(
    'ReservationCountAggregateInput',
    {
        'id': bool,
        'date': bool,
        'tableId': bool,
        'memberId': bool,
        'status': bool,
        'partySize': bool,
        'notes': bool,
        'createdAt': bool,
        'updatedAt': bool,
        '_all': bool,
    },
    total=False,
)

ReservationCountAggregateOutput = TypedDict(
    'ReservationCountAggregateOutput',
    {
        'id': int,
        'date': int,
        'tableId': int,
        'memberId': int,
        'status': int,
        'partySize': int,
        'notes': int,
        'createdAt': int,
        'updatedAt': int,
        '_all': int,
    },
    total=False,
)


ReservationKeys = Literal[
    'id',
    'date',
    'tableId',
    'table',
    'memberId',
    'member',
    'status',
    'partySize',
    'notes',
    'createdAt',
    'updatedAt',
]
ReservationScalarFieldKeys = Literal[
    'id',
    'date',
    'tableId',
    'memberId',
    'status',
    'partySize',
    'notes',
    'createdAt',
    'updatedAt',
]
ReservationScalarFieldKeysT = TypeVar('ReservationScalarFieldKeysT', bound=ReservationScalarFieldKeys)

ReservationRelationalFieldKeys = Literal[
        'table',
        'member',
    ]



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields